create table if not exists public.alisha_profiles (
  visitor_id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visit_day_keys jsonb not null default '[]'::jsonb,
  affinity integer not null default 0,
  section_visits jsonb not null default '{}'::jsonb,
  preferences jsonb not null default '{}'::jsonb
);

create table if not exists public.alisha_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  visitor_id uuid not null references public.alisha_profiles(visitor_id) on delete cascade,
  event_type varchar(48) not null,
  content_type varchar(32),
  content_id varchar(96),
  memory_id varchar(96),
  context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists alisha_events_visitor_created_idx
  on public.alisha_events(visitor_id, created_at desc);

create table if not exists public.alisha_memory_deliveries (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null references public.alisha_profiles(visitor_id) on delete cascade,
  memory_id uuid not null unique,
  content_type varchar(32) not null,
  content_id varchar(96) not null,
  reason_code varchar(48) not null,
  action varchar(24) not null default 'delivered',
  delivered_at timestamptz not null default now(),
  acted_at timestamptz
);

create index if not exists alisha_deliveries_recent_idx
  on public.alisha_memory_deliveries(visitor_id, delivered_at desc);

alter table public.alisha_profiles enable row level security;
alter table public.alisha_events enable row level security;
alter table public.alisha_memory_deliveries enable row level security;

-- 2026 年起新表可能不会自动暴露给 Data API，因此显式授权 service_role。
grant usage on schema public to service_role;
grant select, insert, update, delete on table
  public.alisha_profiles,
  public.alisha_events,
  public.alisha_memory_deliveries
to service_role;
grant usage, select on sequence
  public.alisha_events_id_seq,
  public.alisha_memory_deliveries_id_seq
to service_role;

-- 浏览器不能直连这些表；只有服务端的 service role 可以访问。
revoke all on table
  public.alisha_profiles,
  public.alisha_events,
  public.alisha_memory_deliveries
from anon, authenticated;
