create table if not exists public.alisha_profiles (
  visitor_id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visit_day_keys jsonb not null default '[]'::jsonb,
  affinity integer not null default 0,
  section_visits jsonb not null default '{}'::jsonb,
  preferences jsonb not null default '{}'::jsonb
);

create table if not exists public.alisha_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  visitor_id uuid not null references public.alisha_profiles(visitor_id) on delete cascade,
  event_type varchar(48) not null,
  content_type varchar(32),
  content_id varchar(96),
  memory_id varchar(96),
  context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists alisha_events_visitor_created_idx
  on public.alisha_events(visitor_id, created_at desc);

create table if not exists public.alisha_memory_deliveries (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null references public.alisha_profiles(visitor_id) on delete cascade,
  memory_id uuid not null unique,
  content_type varchar(32) not null,
  content_id varchar(96) not null,
  reason_code varchar(48) not null,
  action varchar(24) not null default 'delivered',
  delivered_at timestamptz not null default now(),
  acted_at timestamptz
);

create index if not exists alisha_deliveries_recent_idx
  on public.alisha_memory_deliveries(visitor_id, delivered_at desc);

alter table public.alisha_profiles enable row level security;
alter table public.alisha_events enable row level security;
alter table public.alisha_memory_deliveries enable row level security;

-- 2026 年起新表可能不会自动暴露给 Data API，因此显式授权 service_role。
grant usage on schema public to service_role;
grant select, insert, update, delete on table
  public.alisha_profiles,
  public.alisha_events,
  public.alisha_memory_deliveries
to service_role;
grant usage, select on sequence
  public.alisha_events_id_seq,
  public.alisha_memory_deliveries_id_seq
to service_role;

-- 浏览器不能直连这些表；只有服务端的 service role 可以访问。
revoke all on table
  public.alisha_profiles,
  public.alisha_events,
  public.alisha_memory_deliveries
from anon, authenticated;

create table if not exists public.alisha_rate_limits (
  bucket_key varchar(160) not null,
  window_start timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  updated_at timestamptz not null default now(),
  primary key (bucket_key, window_start)
);

create index if not exists alisha_rate_limits_window_idx
  on public.alisha_rate_limits(window_start);

alter table public.alisha_rate_limits enable row level security;
grant select, insert, update, delete on table public.alisha_rate_limits to service_role;
revoke all on table public.alisha_rate_limits from anon, authenticated;

create or replace function public.consume_alisha_rate_limit(
  p_bucket_key text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, remaining integer, retry_after integer)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_window_start timestamptz;
  v_count integer;
begin
  if length(p_bucket_key) < 4 or length(p_bucket_key) > 160 then
    raise exception 'invalid rate limit bucket';
  end if;
  if p_limit < 1 or p_limit > 10000 or p_window_seconds < 1 or p_window_seconds > 86400 then
    raise exception 'invalid rate limit parameters';
  end if;

  v_window_start := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  insert into public.alisha_rate_limits(bucket_key, window_start, request_count, updated_at)
  values (p_bucket_key, v_window_start, 1, clock_timestamp())
  on conflict (bucket_key, window_start)
  do update set
    request_count = public.alisha_rate_limits.request_count + 1,
    updated_at = clock_timestamp()
  returning request_count into v_count;

  return query select
    v_count <= p_limit,
    greatest(p_limit - v_count, 0),
    greatest(
      ceil(extract(epoch from (v_window_start + make_interval(secs => p_window_seconds) - clock_timestamp())))::integer,
      1
    );
end;
$$;

revoke execute on function public.consume_alisha_rate_limit(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_alisha_rate_limit(text, integer, integer)
  to service_role;
